package com.example.demo.controller;

import com.example.demo.BackMysqlRestLocaltelApplication;
import com.example.demo.entity.Cuenta;
import com.example.demo.entity.Movimiento;
import com.example.demo.entity.Usuario;
import com.example.demo.repository.ICuentaRepository;
import com.example.demo.repository.IMovimientoRepository;
import com.example.demo.repository.IUsuarioRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

@org.springframework.stereotype.Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class Controller {
	private static final Logger log = LoggerFactory.getLogger(Controller.class);
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private IUsuarioRepository iUsuarioRepository;
	@Autowired
	private ICuentaRepository iCuentaRepository;
	@Autowired
	private IMovimientoRepository iMovimientoRepository;
	
	@GetMapping(path="/AllUsuario")
	public @ResponseBody
	List<Usuario> getAllUsuario() {
		// This returns a JSON Usuario
		return iUsuarioRepository.findAll();
	}
	
	@GetMapping(path="/AllMovimiento")
	public @ResponseBody
	List<Movimiento> getAllMovimiento() {
		// This returns a JSON Movimiento
		return iMovimientoRepository.findAll();
	}
	
	@GetMapping(path="/AllCuenta")
	public @ResponseBody
	List<Cuenta> getAllCuenta() {
		// This returns a JSON Cuenta
		return iCuentaRepository.findAll();
	}

	

}
